### ISSUE TITLE
Wrap struct definition in a module

### ISSUE THREAD

**Issue by freitagbr** [freitagbr/crystal-uvarint#6]
In order to avoid namespace conflicts, the `struct UVarInt` definition should be placed inside a `module`.

**Comment by nfischer** [comment]
Does that actually reduce namespace conflicts? If we name our module `Foo` and another module is named `Foo`, isn't that a namespace conflict?

**Comment by freitagbr** [comment]
Yes that would be a namespace conflict. It at least reduces the surface for name conflicts.

Thinking about it more, it might not be a necessary in our situation, because we are only exporting 1 thing, the struct, and I would probably name the module the same as the struct (`UVarInt`).

**Comment by freitagbr** [comment]
I'll close this for now. Maybe we can revisit this in the future.
